[package]
name = "carr"
description = "Constant-sized arrays using const generics"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"
repository = "https://github.com/CATboardBETA/carr"
keywords = ["nightly", "array", "const-generics", "matrix", "tensor"]
categories = ["mathematics", "data-structures", "science", ]
authors = ["CATboardBETA"]

[dependencies]
itertools = "0.15.0"
rand = { version = "0.10.2", optional = true }

[features]
default = []
full = ["rand"]
rand = ["dep:rand"]